### ISSUE TITLE
Move Tickets to a vendor module

### ISSUE THREAD

**Issue by tdutrion** [conferencetools/opentickets#48]
I propose a re-organisation of the project with the following:

- conferencetools/opentickets: a ZF2/3 module (basically the `module/Tickets` from the current project.
- conferencetools/opentickets-skeleton-application: a skeleton application with documentation
- conferencetools/opentickets-yorkshirephp: a module similar to [scotlandphp/opentickets-scotlandphp](https://github.com/scotlandphp/opentickets-scotlandphp) that overrides views and could also set tickets prices as it's public knowledge anyway.
- conferencetools/opentickets-skeleton-module: a skeleton module for customisation by any other conference, fully commented.

This still leave a major concern, namely the asset management... For now I have only used CDN as we are planning for an integration within an iframe with very little style.

**Comment by carnage** [comment]
This is something I am working towards in order to better support the range of tools I intend to build under the conference tools "brand"

The assets were the largest hurdle for this being a smooth process so I have done a review of the various ZF2 asset managers and will be looking to integrate one of them soon.

**Comment by carnage** [comment]
Closing this, as it the bulk has now been done.
